sonar.projectKey=timesheet
sonar.projectName=timesheet
sonar.projectVersion=1.0

sonar.sources=.

sonar.host.url=http://localhost:9000

sonar.token=sqa_28f1bad394b7fcb2994bc274c72c7aaccb093cac
sonar.java.binaries=target/classes
sonar.exclusions=**/*.zip,**/sonar-scanner-*.zip,**/node_modules/**,**/target/**
